### ISSUE TITLE
It seems a nice project but sir am having an issue plz look after it...

### ISSUE THREAD

**Issue by ShrimantaGarain** [0x0is1/sweet-dreams#1]
![image](https://user-images.githubusercontent.com/51848590/151648937-5700c56f-1c3c-4051-957c-0d0a91753f04.png)

**Comment by 0x0is1** [comment]
Hey Shri,
I think the problem is with new `ffplay` binary that it may not have `-window_title` feature, or they may have changed it to something else (will figure out later)
Altho it does not matter alot, as it is just setting title of the window, so we can remove it as well.

And i can't do it right now as i don't have my pc with me. So can you do me a favour in correction?

In sdlib/sdlib.py at `play` function, remove ` -window_title '{title}'` and check if it works

Thank you

**Comment by ShrimantaGarain** [comment]
after removing -window_title '{title}'  : 

def play(file_url, title): 
    os.system(f"ffplay '{file_url}' ")


error: 

![Screenshot (6)](https://user-images.githubusercontent.com/51848590/151669457-ef6f9056-7cf1-4664-bce3-5cd826253b5f.png)

**Comment by 0x0is1** [comment]
Try exchanging quotations:
```
def play(file_url, title):
    os.system(f'ffplay "{file_url}"')
```

**Comment by ShrimantaGarain** [comment]
its working great after that fix ................... for an enhancement purpose can u design a GUI?

Thanks Brother!!

**Comment by 0x0is1** [comment]
Thanks for reaching out for that purpose. Will commit this issue.

Talking of GUI, definitely it's on my list but it will be a Qt C++ app i don't think most of the people knows how to use it. But yeah still, i will make one soon. But not android app, just a desktop app.

Thanks for suggestion and this issue as well.

**Comment by 0x0is1** [comment]
Issue resolved.
